/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_example_CsvDriver */

#ifndef _Included_org_example_CsvDriver
#define _Included_org_example_CsvDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_CsvDriver
 * Method:    nativeExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_CsvDriver_nativeExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
